steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/resume-api:$COMMIT_SHA', '-f', 'apps/api/Dockerfile', '.']
    dir: '/'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resume-api:$COMMIT_SHA']
    id: 'push-image'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'resume-api'
      - '--image=gcr.io/$PROJECT_ID/resume-api:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=1'
      - '--set-env-vars=RESUME_ENV=$_RESUME_ENV,GITHUB_TOKEN=$_GITHUB_TOKEN,RESUME_GEMINI_API_KEY=$_RESUME_GEMINI_API_KEY'
    id: 'deploy-cloud-run'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/resume-api:$COMMIT_SHA'

# Substitution variables to be supplied when triggering the build
substitutions:
  _RESUME_ENV: 'prd'  # Default value, can be overridden when triggering

# Timeout for the entire build process
timeout: '1800s'